### ISSUE TITLE
Add support for symfony/process ^6.0

### ISSUE THREAD

**Issue by khalyomede** [tarfin-labs/zbar-php#6]
**Is your feature request related to a problem? Please describe.**

To support project that rely on symfony/process:^6.0.

**Describe the solution you'd like**

Testing with symfony/process ^6.0.

**Describe alternatives you've considered**

Forking.

**Additional context**

It's because I use Laravel 9 (which rely on symfony/process:^6.0).

**Comment by frkcn** [comment]
Hi @khalyomede 

This [PR ](https://github.com/tarfin-labs/zbar-php/pull/5/files) add both PHP 8.1 and symfony/process ^6.0 support. New release 1.3.0 published.
